version: "3.8"
services:
  postgresql:
    image: postgres:15.2
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
    networks:
      - sonarqube
    volumes:
      - postgresql:/var/lib/postgresql

  sonarqube:
    image: sonarqube:9.9.0-community
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonar
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_WEB_JAVA_OPTS: "-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError"
      SONAR_CE_JAVA_OPTS: "-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError"
      SONAR_ES_JAVA_OPTS: "-Xmx1g -Xms512m -XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "9000:9000"
    networks:
      - sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - postgresql

networks:
  sonarqube:

volumes:
  postgresql:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
